version: 2
jobs:
  compile_tests:
    machine: true
    environment:
     SBT_SCALA_VERSION: 2.11.7
     SBT_OPTS: -XX:+CMSClassUnloadingEnabled
     JAVA_OPTS: "-Xms1g -Xmx3g -XX:MetaspaceSize=512M -XX:+UseConcMarkSweepGC -Xss256m"
     TZ: Europe/Berlin
    working_directory: ~/TestCircleCi
    steps: 
      - run: 
          name: install_sbt
          command: wget -O /tmp/sbt-0.13.13.deb https://dl.bintray.com/sbt/debian/sbt-0.13.13.deb && sudo dpkg -i /tmp/sbt-0.13.13.deb
      - checkout
      - run:
          name: complie_code
          command: sbt -v test:compile
          
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - compile_tests
